
###################################
# Site wide configuration
###################################

title: TheCapo
short: Capture the Flag write ups
description: "all about my journey into security, walkthrough, CTF, reverse engineering, and exploit development."
url: https://thecapo.com
keywords: ["security", "walkthrough", "CTF", "reverse engineering", "exploit development"]


###################################
# Jekyll configuration
###################################

timezone:          EST
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

####################################
# Site Owner configuration
####################################

owner:
  name: Chance P
  logo: logo.png
  avatar: bernie.png
  shoutout: "1337"
  job:
  bio: "A security enthusiast. Avid Gamer"
  email: capearso@ualberta.ca
  twitter: thecapo
  facebook: #username
  google:
    plus: #username
    analytics: UA-113897290-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  keybase: #username
  github: capearso
  stackoverflow: #username
  linkedin: capearso
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username

####################################
# Plugins
####################################

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-paginate

paginate: 3
paginate_path: "/:num/"

theme: jekyll-theme-hacker
