###################################
# Site wide configuration
###################################

title: TheCapo
short: my security journeyF
description: "all about my journey into security, walkthrough, CTF, reverse engineering, and exploit development."
url: https://capearso.com
keywords: ["security", "walkthrough", "CTF", "reverse engineering", "exploit development"]


###################################
# Jekyll configuration
###################################

timezone:          EST
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

####################################
# Site Owner configuration
####################################

owner:
  name: Chance P
  logo: logo_vawh6v.png
  avatar: bernie.png
  shoutout: "1337"
  job:
  bio: "A security enthusiast. Likes cats."
  email: capearso@ualberta.ca
  disqus-shortname: thecapo
  twitter: thecapohs
  facebook: #username
  google:
    plus: #username
    analytics: UA-166781006-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  keybase: #username
  github: capearso
  stackoverflow: #username
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
  reddit: #username

####################################
# Plugins
####################################

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-paginate

paginate: 3
paginate_path: "/:num/"

#theme: jekyll-theme-hacker
theme: jekyll-theme-midnight


