
###################################
# Site wide configuration
###################################

title: /security
description: My security journey
url: https://limbernie.github.io
keywords: ["security", "walkthrough", "CTF", "reverse engineering", "exploit development"]


###################################
# Jekyll configuration
###################################

timezone:          UTC
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

####################################
# Site Owner configuration
####################################

owner:
  name: Bernie Lim
  avatar: avatar.png
  job: 
  bio: "A security ethusiast. Likes cats."
  email: #email
  disqus-shortname: limbernie
  twitter: limbernie
  facebook: #username
  google:
    plus: #username
    analytics: UA-113897290-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: limbernie
  stackoverflow: #username
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username

####################################
# Plugins
####################################

plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
